source 'https://cdn.cocoapods.org'

platform :ios, '16.0'

target 'WishApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'shared', :path => '../shared'

end
